// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuqtotvycdabjveywtts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1cXRvdHZ5Y2RhYmp2ZXl3dHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDEzMDUsImV4cCI6MjA3MDQ3NzMwNX0.CUmg0Ii0mIPlTqAYbDLKRXaJ7oXFrKqx12EN7u76wQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});